### PR TITLE
Update liberation-fonts-ttf URL

### PR DESCRIPTION
**Pull request by prof-ninjason**
The previous URL is broken and created a compile stoppage.

### CODE REVIEW

**Comment by Ntemis** [comment]
This repo is no longer maintained

**Comment by prof-ninjason** [comment]
Thanks.

**Comment by Ntemis** [comment]
You are welcome to sent PR's in this one
https://github.com/libretro/Lakka-LibreELEC

**Comment by prof-ninjason** [comment]
I seen it was for fixed in March. I’m using their patch for my fork of the legacy version for legacy NVidia for my old laptop.

**Comment by samdawat** [comment]
kl

**Pull request closed without merging**
