### PR TITLE
Enable Getty & Login in Busybox for UART Login

### PR DESCRIPTION
**Pull request by bsilvereagle**
Many dev boards (in particular RPi and RPi2) have a hardware UART interface. Currently the only way to get a shell in Lakka is via ssh. In some situations, it is not possible/desirable to setup a network to ssh in to the RPi/2. Enabling Getty in busybox allows a shell to be spawned on the hardware UART interface. 

Note: A user will still have to place `/sbin/getty -L ttyAMA0 115200 vt100` in either `autostart.sh` or self-compile as a system.d service.

### CODE REVIEW

**Comment by Kivutar** [comment]
Hello, and thanks for the PR. I have been using UART on the Cubieboard 2 and the Odroids without enabling this in busybox. Are you 100% sure that this change is required?

**Comment by bsilvereagle** [comment]
I'm nearly 100% confident on the RPi/2 requiring this. 

When you say "using UART" are you getting a prompt, or just kernel booting debug logs?

**Comment by Kivutar** [comment]
I did get a prompt, if I recall correctly. Anyway, it's a change that should not break anything, and if you say that it is required for the RPi/2 I trust you.

**Comment by bsilvereagle** [comment]
Not only does it not break anything, but it also doesn't use any resources until activated by a user, it just takes up a little more space in the busybox executable. 

Thanks for pulling!

**Comment by Kivutar** [comment]
I got a kernel panic, and reverting this commit fixed it. Did you notice anything similar on a fresh install?

**Comment by bsilvereagle** [comment]
No I did not, what hardware? 

If it introduces issues on other platforms, I'd revert it back. I've only tested on Rpi/2.

**Comment by Kivutar** [comment]
On RPi2.

**Comment by bsilvereagle** [comment]
I had a chance to spin up some VMs and play around with this some more. 

From scratch, with the above configuration in busybox.conf I also receive the kernel panic on both RPi/2. 

However, if you fresh install with a 'clean' Lakka image, and swap out the KERNEL and SYSTEM with those compiled with the above busybox configs, everything is fine and getty is accessible. 

My suggestion (which I think you've already done) is to revert the busybox.conf and this PR can serve as documentation for people who want a UART on the RPi/2. 

Sorry for the trouble!

**Comment by Kivutar** [comment]
Do you have any idea where the bug comes from then?

**Comment by bsilvereagle** [comment]
I was able to repro it in OpenELEC yesterday as well. 

No I do not what is causing the issue. I imagine it must be a busybox issue and probably not a buildroot issue. I'm going to dig around in Sabotage Linux when I get some more free time and see how their busybox is configured.

**Pull request merged**
