### PR TITLE
Add udev rule for JUYAO Dual Arcade

### PR DESCRIPTION
**Pull request by gouchi**
[Source](http://libretro.com/forums/showthread.php?t=6360&page=2&p=43076&viewfull=1#post43076)

### CODE REVIEW

**Comment by GeoDragon30** [comment]
Is this in the latest release of Lakka?

**Comment by gouchi** [comment]
Yes and it is in `/usr/lib/udev/rules.d`

**Comment by GeoDragon30** [comment]
Not sure if this is where I would report this, but the Juyao controller in input one and two show as (#1). I am not an expert in any way on Linux but I do have putty/ip address if there are commands I should run to make this work. Would anyone be able to help with this issue?

**Comment by gouchi** [comment]
Please read the [documentation](http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/#ssh). You are using [latest release](http://www.lakka.tv/get/windows/generic) ? You can come on [our channel](http://webchat.freenode.net/?channels=%23lakkatv) to get direct help.

**Comment by GeoDragon30** [comment]
I did read the doc. I will try the Channel and forum next. Thank you for your time.

**Comment by GeoDragon30** [comment]
gouchi - I signed up in the forum to create a post but never received the verification email, not even in spam.junk folder. I found a post you helped someone with -"Problems with controls "juyao dual arcade"" and tried everything I saw there but to know avail. Any other ideas you might have? I did pull the same information from Lakka using SSH, you had pi0lin do if you need those as well.

**Pull request merged**
